### PR TITLE
Advise users that the wiki is deprecated.

### PR DESCRIPTION
**Pull request by flexibeast**
Cf. https://github.com/void-linux/void-docs/issues/104.

### CODE REVIEW

**Comment by flexibeast** [comment]
Ping?

**Comment by Vaelatern** [comment]
lgtm

**Comment by bobertlo** [comment]
@Duncaen @Vaelatern @the-maldridge ping

**Comment by anjandev** [comment]
@flexibeast It might be worthwhile to mention what the void-docs project should include (just a link). Also, asking people to clean up wiki articles they find useful and fit the void-docs objective to send pull requests.

Basically summarizing the github issue on deprecation discussion.

**Comment by flexibeast** [comment]
Updated PR to explicitly mention that the wiki is no longer being maintained.

**Comment by Duncaen** [comment]
Added the message, the wiki doesn't use this repo since a few versions.

**Comment by flexibeast** [comment]
Excellent, thanks!

**Pull request closed without merging**
